### ISSUE TITLE
Number of fit parameters

### ISSUE THREAD

**Issue by BAllanach** [smelli/smelli#32]
When using smelli to calculate a p-value, I need to know the number of fit parameters, if they are profiled over (for example in the electroweak likelihood, one often uses say M_W both as an input parameter and as an output parameter).
Where may I find this information, please?

**Comment by DavidMStraub** [comment]
Hi Ben, the nuisance parameters in smelli are not profiled over or marginalized, since this would be dependent on the Wilson coefficients. Instead, the theory uncertainties of all observables are assumed to be multivariate Gaussians and to be unaffected by new physics. They are then combined with the experimental uncertainties. This approximation depends on several conditions to be justified, as discussed in https://arxiv.org/pdf/1810.07698.pdf#section.2, but has the advantage of being very fast. Following this approach, for the p-value all that is needed is the number of observables. There are some subtleties and caveats, as discussed in https://arxiv.org/pdf/1903.10434.pdf#appendix.B.

That being said, `smelli` is essentially a convient, predefined likelihood built with `flavio`, which can be used with an arbitrary statistical framework. It would be straightforward to build a likelihood with flavio's `Likelihood` class (possibly even derived from smelli's `GlobalLikelihood`) that does not use the "nuisance-free" approach and where nuisance parameters can be varied by passing different parameter values via the `par_dict` dictionary.
