### ISSUE TITLE
Changing CKM inputs

### ISSUE THREAD

**Issue by MJKirk** [smelli/smelli#33]
If I want to change the experimental inputs used for the CKM determinations, how do I do this?

Just naively I tried doing
```python
smelli.flavio.Measurement('CKM ratio measurements').set_constraint('RKpi(P+->munu)', '1.3368+-0.0031')
```
(which is just a tiny change in the uncertainty from 0.0032 to 0.0031 so I would expect nothing terrible to happen) before creating my `GlobalLikelihood` and doing a fit, but then you get an error: `ValueError: The extraction of CKM elements failed. Too large NP effects?`

Looking more closely at the code, do you actually have to change the values in `ckm.py`
https://github.com/smelli/smelli/blob/50c4da155f737aaf80aa48744ad614f542d5478d/smelli/ckm.py#L9-L10
and then run `update_ckm.py` and/or `save_covariances.py` manually?
You can't easily do this as an end user, since those python scripts don't get installed (because of these settings:
https://github.com/smelli/smelli/blob/50c4da155f737aaf80aa48744ad614f542d5478d/setup.py#L21-L23
only the `*.yaml ` and `*.p` get installed).

Having written all that, I realise the "deal" with smelli is everything is preset, so really you aren't supposed to change anything like this. :thinking:

**Comment by peterstangl** [comment]
You only have to run `update_ckm.py` and `save_covariances.py` if you want to recompute the SM covariance matrix with the CKM elements determined from your input parameters. In principle this should be done such that everything is consistent, but this takes some time and is usually not done by the user.

However, I think there is a basic problem with your code
```python
smelli.flavio.Measurement('CKM ratio measurements').set_constraint('RKpi(P+->munu)', '1.3368+-0.0031')
```
since `smelli.flavio.Measurement('CKM ratio measurements')` creates a new instance with name `'CKM ratio measurements'` and overwrites the old one. You don't set the constraint for `DeltaM_d/DeltaM_s`, which is also needed. So the first error you get should actually be
```
ValueError: No experimental measurements found for this observable.
```
And then `During handling of the above exception, another exception occurred:` and the second error should then be `ValueError: The extraction of CKM elements failed. Too large NP effects?`.

You can avoid this by setting the constraints also for `DeltaM_d/DeltaM_s`, i.e. by replacing your line of code with
```python
# overwrite the measurement instance with an empty new one
m = smelli.flavio.Measurement('CKM ratio measurements') 

# set your own constrains
m.set_constraint('RKpi(P+->munu)', '1.3368+-0.0031')
m.set_constraint('DeltaM_d/DeltaM_s', '0.02852+-0.00011') 
```
But keep in mind that the precomputed SM covariance matrix might not be fully consistent with this setting.

**Comment by MJKirk** [comment]
Thanks - that is actually the first error I get. That'll teach me to always scroll up and check :facepalm:.

Am I correct in believing 
```python
# get the current measurement instance
m = smelli.flavio.Measurement['CKM ratio measurements']

# set your own constrains
m.set_constraint('RKpi(P+->munu)', '1.3368+-0.0031')
```
should do the same thing without needing to re-set `DeltaM_d/DeltaM_s` which I am not changing?

Yeah, the consistency of everything is what I worried about when I started digging. I'm also interested in changing various other parameters so quite a lot of the uncertainties/covariances could change.
I guess for "small" changes it's not a problem, but knowing what counts as small is the issue.

**Comment by peterstangl** [comment]
> Am I correct in believing
> 
> ```python
> # get the current measurement instance
> m = smelli.flavio.Measurement['CKM ratio measurements']
> 
> # set your own constrains
> m.set_constraint('RKpi(P+->munu)', '1.3368+-0.0031')
> ```
> 
> should do the same thing without needing to re-set `DeltaM_d/DeltaM_s` which I am not changing?

Yes, I think this should also work.

> Yeah, the consistency of everything is what I worried about when I started digging. I'm also interested in changing various other parameters so quite a lot of the uncertainties/covariances could change.
> I guess for "small" changes it's not a problem, but knowing what counts as small is the issue.

Yes, if you change several input parameters, it's probably good to recompute the covariance matrix.
